from __future__ import annotations

from typing import Protocol

from rateforge.domain.users.entities import User


class UserRepository(Protocol):
    async def add(self, entity: User) -> User: ...
    async def get(self, entity_id: str) -> User | None: ...
    async def list(self) -> list[User]: ...
    async def get_by_email(self, email: str) -> User | None: ...
