from __future__ import annotations

from typing import Any, Protocol


class ProductPlugin(Protocol):
    version: str
    config: dict[str, Any]

    def validate(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def calculate(self, payload: dict[str, Any]) -> dict[str, Any]: ...
    def renew(self, existing_quote: dict[str, Any]) -> dict[str, Any]: ...
    def endorsement(self, existing_quote: dict[str, Any], changes: dict[str, Any]) -> dict[str, Any]: ...
    def summary(self, payload: dict[str, Any]) -> dict[str, Any]: ...
