from __future__ import annotations

from typing import Protocol

from rateforge.domain.products.entities import ProductDefinition


class ProductRepository(Protocol):
    async def add(self, entity: ProductDefinition) -> ProductDefinition: ...
    async def get(self, entity_id: str) -> ProductDefinition | None: ...
    async def get_by_slug(self, slug: str, version: str | None = None) -> ProductDefinition | None: ...
    async def list(self) -> list[ProductDefinition]: ...
